version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: big-bear-umbrel-chromium_server_1
      APP_PORT: 8000

  server:
    image: portainer/portainer-ce:latest
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${APP_DATA_DIR}/data/portainer/data:/data
