version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: big-bear-umbrel-guacamole_frontend_1
      APP_PORT: 8080
      PROXY_AUTH_ADD: "false"

  frontend:
    image: guacamole/guacamole
    environment:
      - MYSQL_DATABASE=guacamole_db
      - MYSQL_USER=guacamole_user
      - MYSQL_PASSWORD=a49cd326-af4e-4a76-9995-51fc2b7bd58f
    restart: on-failure
    depends_on:
      - guacd
      - db

  guacd:
    image: guacamole/guacd
    restart: always

  db:
    image: mysql:8.0
    restart: on-failure
    volumes:
      - ${APP_DATA_DIR}/data/guacamole/db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: "a49cd326-af4e-4a76-9995-51fc2b7bd58f"
      MYSQL_USER: "guacamole_user"
      MYSQL_PASSWORD: "a49cd326-af4e-4a76-9995-51fc2b7bd58f"
      MYSQL_DATABASE: "guacamole_db"
