version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: uptime-kuma_server_1
      APP_PORT: 3001

  server:
    image: louislam/uptime-kuma:1.22.1@sha256:8223121cd8772aca3b52146ac4b5460c9b1daedb
    restart: on-failure
    stop_grace_period: 1m
    volumes:
      - ${APP_DATA_DIR}/data/uptime-kuma:/app/data
